### ISSUE TITLE
imagePullSecrets not recognized at the container spec level

### ISSUE THREAD

**Issue by eflynn-istream** [spotinst/spotinst-kubernetes-helm-charts#27]
**What happened**:
In order to avoid being rate limited by docker, I have added a secret to be used to pull images. I have defined my spotinst.yaml template as:
```
spotinst:
  token: {{ .Values.spotinst.token }}
  account: {{ .Values.spotinst.account }}
  clusterIdentifier: {{ .Values.cluster }}
  disableAutoUpdate: true

metrics-server:
  deployChart: false

image:
  pullSecrets:
  - name: secretname
```
With this configuration, Kubernetes is not recognizing my secret. 
In the spec, I see that the `imagePullSecret` is defined at the [container level](https://github.com/spotinst/spotinst-kubernetes-helm-charts/blob/master/charts/spotinst-kubernetes-cluster-controller/templates/deployment.yaml#L25-L32). 

**What you expected to happen**:
While `imagePullSecrets` is rendered "correctly" in the helmfile according to the `deployment.yaml`, the final k8s resource does not include it on the Pod.

Kubernetes should recognize the secret at the pod spec level (rather than container) according to the [official API/spec definition](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#podspec-v1-core). I believe a slight change is needed in the `deployment.yaml` file to move the `imagePullSecrets` up one level. 

Thank you! Please let me know if you need any more info/detail.
